DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Topic;
DROP TABLE IF EXISTS Forum;
DROP TABLE IF EXISTS Person;

CREATE TABLE Person (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    username VARCHAR(10) NOT NULL UNIQUE,
    stuId VARCHAR(10) NULL
);

CREATE TABLE Forum (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE Topic (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(30) NOT NULL,
    message VARCHAR(500) NOT NULL,
    forumId INTEGER NOT NULL,
    personId INTEGER NOT NULL,
    FOREIGN KEY (personId) REFERENCES Person(id),
    FOREIGN KEY (forumId) REFERENCES Forum(id)
);

CREATE TABLE Post (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    message VARCHAR(500) NOT NULL,
    topicId INTEGER NOT NULL,
    personId INTEGER NOT NULL,
    FOREIGN KEY (personId) REFERENCES Person(id),
    FOREIGN KEY (topicId) REFERENCES Topic(id)
);
